
AUTOSTART
SET_TRACK(B, MAIN)
SET_POWER(A, ON)
SET_POWER(B, ON)
DONE

TURNOUTL(5, 5, "Factory 5")
TURNOUTL(6, 6, "Inner   6")
TURNOUTL(7, 7, "Outer   7")

ROUTE(11, "Loop")
  THROW(5)
  CLOSE(6)
  THROW(7)
  RETURN

ROUTE(12, "Stage")
  THROW(6)
  CLOSE(7)
  RETURN

  
ROUTE(13, "Inner-Factrory")
  THROW(5)
  THROW(6)
  RETURN

ROUTE(14, "Inner-Brigde")
  CLOSE(5)
  THROW(6)
  RETURN

// AUTOMATIONS

ALIAS(OUT, "OUT"_hk)
ALIAS(PARK, "PARK"_hk)
ALIAS(ENDIT, "ENDIT"_hk)
#define DEL_FACT 7000
#define DEL_CRAWL 32000
#define DEL_LOAD 5000
#define DEL_OUT 20000
#define DEL_IN  31000
#define DEL_PARK 10000

#define SPEED_CRAWL 3
#define SPEED_SLOW 50

SEQUENCE(5) // LOADING
  DELAY(DEL_LOAD)
  FWD(SPEED_CRAWL)
  DELAY(DEL_CRAWL)
  STOP
RETURN

AUTOMATION(OUT, "X Start show") //out of tunnel
  LATCH(200)
  FWD(SPEED_SLOW)
  FON(0)
  DELAY(DEL_FACT)
  FWD(SPEED_CRAWL)
  DELAY(15000)
  STOP
  CALL(5)
  CALL(5)
  CALL(5)
  DELAY(DEL_LOAD)
  FWD(SPEED_SLOW)
  DELAY(DEL_OUT)
  FWD(SPEED_CRAWL)
  DELAY(1000)
  STOP
  FOFF(0)
  IF (200)
    DELAYRANDOM(5000,10000)
    FOLLOW(PARK)
  ENDIF
DONE

AUTOMATION(PARK, "X Park to tunnel") // into tunnel
  REV(SPEED_SLOW)
  FON(0)
  DELAY(DEL_IN)
  REV(SPEED_CRAWL)
  DELAY(DEL_PARK)
  STOP
  FOFF(0)
  IF (200)
    DELAYRANDOM(5000,20000)
    FOLLOW(OUT)
  ENDIF
DONE

AUTOMATION(ENDIT, "X End Shuttle")
  UNLATCH (200)
DONE
